language: ruby
rvm:
- 2.4.1
services:
- postgresql
- redis-server
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database Van_CSV_Uploader_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
env:
- DB=pgsql
