language: ruby
rvm:
- 2.4.1
before_script:
  - psql -c 'create database Van_CSV_Uploader_test;' -U postgres
services:
- postgresql
- redis-server
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rspec
env:
  global:
    secure:
