language: ruby
rvm:
- 2.4.1
services:
- postgresql
- redis-server
before_script:
  - psql -c 'create database Van_CSV_Uploader_test;' -U postgres
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rspec
env:
- DB=pgsql
